### ISSUE TITLE
Does this work with Webpack 3?

### ISSUE THREAD

**Issue by mattdsteele** [smooth-code/error-overlay-webpack-plugin#12]
It's going to be a little while before my org can upgrade to Webpack 4, but I'd love to give this a shot now. Based on [this comment](https://github.com/smooth-code/error-overlay-webpack-plugin/issues/8#issuecomment-373418228), I'm curious if it would work with older version of Webpack?

**Comment by neoziro** [comment]
I think it will not work on Webpack 3, but it could be, a few minor changes are required to add support. PR welcome.

**Comment by neoziro** [comment]
This is not plan for now, no Webpack 4, no error overlay 😆
