### ISSUE TITLE
Does not seem to work with webpack-serve - the new dev-server

### ISSUE THREAD

**Issue by swernerx** [smooth-code/error-overlay-webpack-plugin#16]
Hi! Thanks for the plugin. Really appreciated to have this kind of functionality widely available.

I am not exactly sure about details, but it seems like the plugin is not able to work together with [webpack-serve](https://github.com/webpack-contrib/webpack-serve) as a dev-server alternative. It probably registers some middleware to work, but does not correctly detect the alternative dev server config. Do you have any plans for fixing this? Thanks a lot.

**Comment by neoziro** [comment]
Right now I am not on it, but all PR are welcome!

**Comment by budarin** [comment]
I have the problem on webpack-serve too

**Comment by budarin** [comment]
it needs something like this
```js
// discovery fo server option for webpack-serve server
      if (options.serve) {
        // it uses add hook to add any to
        const originalAdd = options.serve.add;

        options.serve.add = (app, middleware, options) => {
          app.use((ctx, next) => errorOverlayMiddleware(ctx.req, ctx.res, next));

          if (originalAdd) {
            originalAdd(app, middleware, options)
          }
        }
      }
```
into ```index.js```

**Comment by victorfern91** [comment]
There is any update regarding this problem?

**Comment by neoziro** [comment]
Could someone fix it in a PR?

**Comment by amertak** [comment]
Webpack-serve is now [DEPRECATED] so I suggest not to fix this anymore and move away from webpack-serve back to webpack-dev-server.
