### ISSUE TITLE
Plugin not working with react-hot-loader

### ISSUE THREAD

**Issue by ioanungurean** [smooth-code/error-overlay-webpack-plugin#19]
Hi, I tried to include your plugin in my app but I could not find a way. There is no error or something similar. When I try to raise an error on purpose nothing happens. I can only see the stack trace in the console.

Did you try with `react-hot-loader`? Maybe I''m missing something.

**Comment by beshanoe** [comment]
As I investigated so far, the issue is not because of react-hot-loader in particular. I'm using custom solution based on webpack-hot-middleware and error overlay only works if it's entry included to entries list only after webpack-hot-middleware entry. Probably it could help with fixing the issue

**Comment by beshanoe** [comment]
@ioanungurean but it would be much helpful if you provide an example to reproduce

**Comment by ioanungurean** [comment]
@beshanoe thank you for answering. I'm not using `webpack-hot-middleware` but instead i'm using `webpack-dev-server` maybe this is the problem. I will provide an example as soon as I can.

**Comment by ioanungurean** [comment]
This is the folder with the [example](https://github.com/ioanungurean/forge-react-app/tree/error_overlay/forge-react-app). 

It displays the error overlay only if I refresh the page otherwise not.

**Comment by neoziro** [comment]
Yes it is expected, actually it can't work with it. @thekashey

**Comment by ioanungurean** [comment]
@neoziro Hi, to confirm basically I cannot use this plugin with `react-hot-loader` and have the error overlay popup without refreshing the page? This is what are you saying?

I will close this issue if the plugin is not supposed to support this kind of behavior.
