### ISSUE TITLE
Is there anyway to use this without using 'create-react-app'

### ISSUE THREAD

**Issue by tomzaku** [smooth-code/error-overlay-webpack-plugin#29]
I read this: https://github.com/smooth-code/error-overlay-webpack-plugin#usage but it's not working.

Dependences
```
typescript: 3.1.2,
ts-loader: 5.3.3,
webpack: v4,
react: v16.8,
```

**Comment by neoziro** [comment]
Hello @tomzaku, could you please provide a repro example? Thanks.

**Comment by tomzaku** [comment]
@neoziro thanks for your response. I created the repo at [this](https://github.com/tomzaku/react-ts)
In the file src/index.tsx has error at line 6. It throw error at terminal/ console. But it's not working with browser

**Comment by neoziro** [comment]
The error seems to be a TypeScript error, I don't know how it works with TypeScript but it is not officially supported. You are on your own..

**Comment by English3000** [comment]
I also tried using this on my own with TypeScript. I'm getting an error message, but for the same syntax error (a missing `>` on the first tag) the message is different (and much less helpful) than for `create-react-app`

my project:
![image](https://user-images.githubusercontent.com/29601050/54622415-cc669b80-4a26-11e9-9f48-35e704b3a611.png)

CRA:
![image](https://user-images.githubusercontent.com/29601050/54622466-dc7e7b00-4a26-11e9-8f04-fc9f3595f79f.png)

![image](https://user-images.githubusercontent.com/29601050/54622502-ec965a80-4a26-11e9-89f1-5fcfe0fd90c5.png)

**Comment by English3000** [comment]
NVM, getting it like `CRA` now.

**Comment by Herz3h** [comment]
Is this a CRA specific plugin ? Doesn't seem to work with webpack 4 + vuejs 2
