### ISSUE TITLE
Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by d12mnit** [smooth-code/error-overlay-webpack-plugin#32]
when I update to 0.1.7 , my project was broken. 
here is the error message FYI
![image](https://user-images.githubusercontent.com/13366123/54412592-4a2c5d80-472e-11e9-86bf-d998440837b7.png)
and version 0.1.6 works fine for me.

**Comment by tungpin** [comment]
this version is works for me, can you give me an repo or example to reproduce the error?

**Comment by d12mnit** [comment]
I'v resolved this problem, it's my webpack config lead to this error.
``` js
module.exports = {
  //...
  node: {
    console: false,
    global: true,
    process: false,      //   set to true resolved this problem
    //....
  }
};
```
