### ISSUE TITLE
README says eval sourcemap is not supported. Is it still true?

### ISSUE THREAD

**Issue by mohsinulhaq** [smooth-code/error-overlay-webpack-plugin#36]
Is it true for only `eval` sourcemap or all eval-based sourcemaps like `cheap-module-eval-source-map`?

**Comment by neoziro** [comment]
Hello @mohsinulhaq, to be honest, I don't know. Can you try and tell me? If you found something, feel free to submit a PR to adapt the readme.

**Comment by mohsinulhaq** [comment]
Confirmed it doesn't work with any of the eval based sourcemaps.
Tried with:
```
- eval
- eval-source-map
- cheap-eval-source-map
- cheap-module-eval-source-map
```
Closing this issue.
