### ISSUE TITLE
Is this package considered stable?

### ISSUE THREAD

**Issue by bencooper222** [smooth-code/error-overlay-webpack-plugin#40]
I'm not sure if it's intentional or not but the fact that the package version is 0.y.z means that any change is considered a major semver change (https://semver.org/#spec-item-4) which interferes with automatic dependency management tools (like npm update) which tend to strictly follow semver.

If you consider this package stable, please consider incrementing to version 1!

**Comment by neoziro** [comment]
Yeah I should consider releasing it as stable.

**Comment by bencooper222** [comment]
Yeah, I closed the issue because I found out that npm handles stuff slightly different from the semver spec. The semver spec states that when your version is 0.y.z, incrementing y or z is breaking. npm (and probably yarn?) look at most significant digit. So, if the first digit = 0, then incrementing y is a major update and incrementing z is minor.
