### ISSUE TITLE
Sock path is no longer hardcoded in webpack

### ISSUE THREAD

**Issue by Mefu** [smooth-code/error-overlay-webpack-plugin#41]
Code [here](https://github.com/smooth-code/error-overlay-webpack-plugin/blob/master/src/entry-devserver.js#L14-L15) is not correct anymore.

`webpack-dev-server` has `sockPath` option since 3.2.0 and `sockHost, sockPort` options since 3.4.0. It would be nice if this plugin can get options from webpack config, or at least allowed these to be customizable so user can set both options same.

**Comment by neoziro** [comment]
Oh you are right, could you submit a PR to fix it?

**Comment by Mefu** [comment]
Closing issue, since you've merged my PR.
