### ISSUE TITLE
Can this work on the top of webpack-serve?

### ISSUE THREAD

**Issue by natocTo** [smooth-code/error-overlay-webpack-plugin#5]
Hello, I am trying your plugin but not working. It is seems it is neccessary to use webpack-dev-server, is it true? I use Webpack-serve (https://github.com/webpack-contrib/webpack-serve).
Thanks for reply.

**Comment by neoziro** [comment]
Editor opening require `webpack-dev-server` but error overlay will work with or without `webpack-dev-server`.

**Comment by mattdsteele** [comment]
Related: would this plugin work directly with [webpack-dev-middleware](https://github.com/webpack/webpack-dev-middleware)? I haven't been able to get it to run with my toolchain, and I'm not sure what's missing.

**Comment by neoziro** [comment]
Yes it should, the plugin just adds an entry to your Webpack configuration, so technically it should work with all Webpack tools.

The only tricky part is the editor opening, only available with Webpack Dev Server. But it is not « the feature » of this plugin.
