### ISSUE TITLE
Update dependencies for security reasons

### ISSUE THREAD

**Issue by muenzpraeger** [smooth-code/error-overlay-webpack-plugin#68]
Hello!

This package hasn't seen any dependency updates since some time, which may lead to security issues. It would be great if we can get a more recent version published, that is up-to-date (must not necessary with webpack5, but at least the other deps).

Thanks!

**Comment by gregberge** [comment]
Hello @muenzpraeger, I currently don't have time to maintain it, feel free to submit a PR to update deps.

**Comment by xandris** [comment]
Can we please get a new release?

**Comment by jonambas** [comment]
@gregberge New release please? 😄

**Comment by gregberge** [comment]
Done!
